name: release_pipeline
parameters:
- name: storageAccountName
  type: string
pool:
  vmImage: windows-latest
trigger: none
pr: none
resources:
  pipelines:
  - pipeline: buildPipelineResource
    source: build pipeline
    branch: main
    trigger:
      branches:
        include:
        - main
stages: 
- stage: release_stage
  displayName: release stage
  jobs:
  - deployment: release_job
    displayName: release job
    environment: dev
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureCLI@2
            displayName: az deployment
            inputs:
              azureSubscription: devops-101
              scriptType: pscore
              scriptLocation: inlineScript
              inlineScript: |
                az deployment group create --resource-group devops-101 --template-file main.bicep  --parameters `@main.parameters-dev.json
              workingDirectory:  $(Pipeline.Workspace)/buildPipelineResource/iac
          - task: AzureFileCopy@5
            displayName: az copy dist
            inputs:
              SourcePath: $(Pipeline.Workspace)/buildPipelineResource/dist/*
              azureSubscription: devops-101
              Destination: AzureBlob
              storage: ${{ parameters.storageAccountName }}
              ContainerName: $web
              CleanTargetBeforeCopy: true